"""
Self-computed Elo ratings for international football.

We walk `results.csv` in chronological order and apply the standard
eloratings.net formula:

    R_new = R_old + K * G * (W - We)

with home advantage of +100 ELO for the non-neutral home team and a
goal-difference multiplier G (1.0 / 1.5 / (11+N)/8 for diff 1 / 2 / >=3).

K is mapped from the `tournament` column with a small lookup so World Cup
matches move ratings more than friendlies.

Returns yearly snapshots (one row per (team, year) using the rating after the
last match of that year), matching the schema produced by
`load_elo_history()` so PoissonModel.fit() can consume it unchanged.

Why self-compute
----------------
The bundled `elo_ratings_wc2026.csv` only covers the 48 WC 2026 qualifiers,
which means PoissonModel silently drops ~87% of historical matches (any
match touching a non-qualifier nation). Computing ELO from results gives
full coverage with no name-matching gaps by construction.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

DEFAULT_INITIAL_RATING = 1500.0
HOME_ADVANTAGE = 100.0

# Cache for the computed ELO history, regenerated by `refresh-data` after new
# match results land. Kept under `data/` (not `data/raw/`) since it's derived.
ELO_CACHE_PATH = Path(__file__).parents[3] / "data" / "elo_history_computed.csv"
# results.csv rows before this year aren't used by the model anyway; bounding
# the input keeps the cache file small and computation fast.
ELO_COMPUTE_MIN_YEAR = 1980


def k_value(tournament: str) -> int:
    """Map tournament name to an Elo K-factor (per eloratings.net conventions)."""
    t = tournament.lower()
    if "world cup" in t and "qualification" not in t:
        return 60
    if "qualification" in t or "qualifying" in t:
        return 40
    continental = (
        "uefa euro",
        "copa américa",
        "copa america",
        "afc asian cup",
        "african cup of nations",
        "africa cup of nations",
        "concacaf gold cup",
        "concacaf nations league",
        "uefa nations league",
        "confederations cup",
    )
    if any(c in t for c in continental):
        return 50
    if "friendly" in t:
        return 20
    return 30


def _goal_diff_multiplier(goal_diff: int) -> float:
    n = abs(int(goal_diff))
    if n <= 1:
        return 1.0
    if n == 2:
        return 1.5
    return (11.0 + n) / 8.0


def elo_delta(
    home_rating: float,
    away_rating: float,
    home_score: int,
    away_score: int,
    neutral: bool,
    tournament: str,
) -> float:
    """Rating change applied to the home team after a match (away team gets ``-delta``).

    The single source of truth for the per-match Elo update, shared by
    ``compute_elo_history`` (offline pass over full history) and the walk-forward
    backtest's sequential update, so the two can never drift apart.
    """
    home_adv = 0.0 if neutral else HOME_ADVANTAGE
    dr = (home_rating + home_adv) - away_rating
    we_h = 1.0 / (1.0 + 10.0 ** (-dr / 400.0))
    if home_score > away_score:
        w_h = 1.0
    elif home_score == away_score:
        w_h = 0.5
    else:
        w_h = 0.0
    return k_value(tournament) * _goal_diff_multiplier(home_score - away_score) * (w_h - we_h)


def compute_elo_history(
    results: pd.DataFrame,
    initial_rating: float = DEFAULT_INITIAL_RATING,
) -> pd.DataFrame:
    """Walk matches in date order, apply Elo updates, return yearly snapshots.

    Output columns: country, year, rating (one row per team per year they
    have a rating at year-end).
    """
    df = results.dropna(subset=["home_score", "away_score"]).copy()
    df = df.sort_values("date").reset_index(drop=True)
    df["year"] = df["date"].dt.year.astype(int)

    elo: dict[str, float] = {}
    snapshots: list[tuple[str, int, float]] = []
    last_year: int | None = None

    home_teams = df["home_team"].tolist()
    away_teams = df["away_team"].tolist()
    home_scores = df["home_score"].astype(int).tolist()
    away_scores = df["away_score"].astype(int).tolist()
    neutrals = df["neutral"].tolist()
    tournaments = df["tournament"].tolist()
    years = df["year"].tolist()

    for h, a, gh, ga, neutral, tourn, y in zip(
        home_teams, away_teams, home_scores, away_scores, neutrals, tournaments, years
    ):
        _ = elo.setdefault(h, initial_rating)
        _ = elo.setdefault(a, initial_rating)

        if last_year is not None and y != last_year:
            for team, rating in elo.items():
                snapshots.append((team, last_year, rating))
        last_year = y

        rh, ra = elo[h], elo[a]
        delta = elo_delta(rh, ra, gh, ga, bool(neutral), str(tourn))
        elo[h] = rh + delta
        elo[a] = ra - delta

    if last_year is not None:
        for team, rating in elo.items():
            snapshots.append((team, last_year, rating))

    return pd.DataFrame(snapshots, columns=["country", "year", "rating"])


def compute_prematch_elo(
    results: pd.DataFrame,
    initial_rating: float = DEFAULT_INITIAL_RATING,
) -> pd.DataFrame:
    """Return each match's *pre-match* Elo ratings — a leak-free training feature.

    Walks matches in date order (same pass as ``compute_elo_history``) and records
    the home/away rating as it stood *before* the match was played. A match's
    feature therefore never reflects its own result nor any later result, unlike
    the year-end snapshots, which tag a March match with its team's December rating.

    Output columns: date, home_team, away_team, home_elo, away_elo (one row per
    scored match, in date order). Compute this over the *full* history so early
    matches carry their true prior ratings, then join onto the training subset.
    """
    df = results.dropna(subset=["home_score", "away_score"]).copy()
    df = df.sort_values("date").reset_index(drop=True)

    elo: dict[str, float] = {}
    home_pre: list[float] = []
    away_pre: list[float] = []

    home_teams = df["home_team"].tolist()
    away_teams = df["away_team"].tolist()
    home_scores = df["home_score"].astype(int).tolist()
    away_scores = df["away_score"].astype(int).tolist()
    neutrals = df["neutral"].tolist()
    tournaments = df["tournament"].tolist()

    for h, a, gh, ga, neutral, tourn in zip(
        home_teams, away_teams, home_scores, away_scores, neutrals, tournaments
    ):
        rh = elo.setdefault(h, initial_rating)
        ra = elo.setdefault(a, initial_rating)
        home_pre.append(rh)
        away_pre.append(ra)
        delta = elo_delta(rh, ra, gh, ga, bool(neutral), str(tourn))
        elo[h] = rh + delta
        elo[a] = ra - delta

    df["home_elo"] = home_pre
    df["away_elo"] = away_pre
    return df[["date", "home_team", "away_team", "home_elo", "away_elo"]]


def load_or_compute_elo_history(force_refresh: bool = False) -> pd.DataFrame:
    """Read the cached computed-ELO CSV, regenerating from results.csv if missing.

    Set `force_refresh=True` to recompute and overwrite the cache — call after
    `results.csv` has been patched with new live results.
    """
    if ELO_CACHE_PATH.exists() and not force_refresh:
        return pd.read_csv(ELO_CACHE_PATH)

    from wc2026.data.loader import load_results

    history = compute_elo_history(load_results(min_year=ELO_COMPUTE_MIN_YEAR))
    ELO_CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    history.to_csv(ELO_CACHE_PATH, index=False)
    return history
